/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Producto.Vistas.Clientes;

import Producto.CapaNegocio.Clientes.Cliente;
import Producto.CapaNegocio.Clientes.DAOCliente;
import java.awt.Event;
import java.awt.Toolkit;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import javax.swing.InputMap;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.KeyStroke;

/**
 *
 * @author Jorge
 */
public class FrmAltaClienteTrampa extends javax.swing.JFrame {

        private Cliente cliente;
    private Boolean altaClienteT;
    /**
     * Creates new form FrmAltaCliente
     */
    public FrmAltaClienteTrampa() {
        initComponents();
        num(txtTrampa);
        this.setDefaultCloseOperation(JFrame.HIDE_ON_CLOSE);
        this.setLocationRelativeTo(null);
        

        altaClienteT= true;
    }
    public FrmAltaClienteTrampa(Cliente c){
        initComponents();
        this.cliente =c;
        this.lblSigId.setText(c.obtenerIdCliente()+"");
        this.txtNombre.setText(c.obtenerNombre());
        this.txtApPaterno.setText(c.obtenerApPaterno());
        this.txtApMaterno.setText(c.obtenerApMaterno());
        this.txtTel.setText(c.obtenerTelefono());
        this.txtTrampa.setText(c.getKilosRobados()+ "");
        InputMap map6 = this.txtNombre.getInputMap(JTextField.WHEN_FOCUSED);
        map6.put(KeyStroke.getKeyStroke(KeyEvent.VK_V, Event.CTRL_MASK),"null");
        InputMap map7 = this.txtApPaterno.getInputMap(JTextField.WHEN_FOCUSED);
        map7.put(KeyStroke.getKeyStroke(KeyEvent.VK_V, Event.CTRL_MASK),"null");
        InputMap map8 = this.txtApMaterno.getInputMap(JTextField.WHEN_FOCUSED);
        map8.put(KeyStroke.getKeyStroke(KeyEvent.VK_V, Event.CTRL_MASK),"null");
        InputMap map9 = this.txtTel.getInputMap(JTextField.WHEN_FOCUSED);
        map9.put(KeyStroke.getKeyStroke(KeyEvent.VK_V, Event.CTRL_MASK),"null");
        InputMap map10 = this.txtTrampa.getInputMap(JTextField.WHEN_FOCUSED);
        map10.put(KeyStroke.getKeyStroke(KeyEvent.VK_V, Event.CTRL_MASK),"null");
        altaClienteT = false;
    }
    private void num(JTextField a)
    {
        a.addKeyListener(new KeyAdapter(){
            public void KeyTyped(KeyEvent e){
                char c  = e.getKeyChar();
                if(!Character.isDigit(c) && c!= '.'){
                    e.consume();
                }
                if(c == '.' && txtTrampa.getText().contains(".")){
                    e.consume();
                }
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jInternalFrame1 = new javax.swing.JInternalFrame();
        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        lblNombre = new javax.swing.JLabel();
        lblApPaterno = new javax.swing.JLabel();
        lblAPnaterno = new javax.swing.JLabel();
        lblTel = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        txtApPaterno = new javax.swing.JTextField();
        txtApMaterno = new javax.swing.JTextField();
        txtTel = new javax.swing.JTextField();
        lblSigId = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtTrampa = new javax.swing.JTextField();
        btbGuardar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        jLabel3.setText("jLabel3");

        jRadioButton1.setText("jRadioButton1");

        jInternalFrame1.setVisible(true);

        javax.swing.GroupLayout jInternalFrame1Layout = new javax.swing.GroupLayout(jInternalFrame1.getContentPane());
        jInternalFrame1.getContentPane().setLayout(jInternalFrame1Layout);
        jInternalFrame1Layout.setHorizontalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jInternalFrame1Layout.setVerticalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Registro de Cliente ");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Alta Cliente con Trampa"));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.setOpaque(false);

        lblNombre.setForeground(new java.awt.Color(0, 0, 0));
        lblNombre.setText("Nombre");

        lblApPaterno.setForeground(new java.awt.Color(0, 0, 0));
        lblApPaterno.setText("Apellido Paterno");

        lblAPnaterno.setForeground(new java.awt.Color(0, 0, 0));
        lblAPnaterno.setText("Apellido Materno");

        lblTel.setForeground(new java.awt.Color(0, 0, 0));
        lblTel.setText("Telefono");

        txtNombre.setBackground(new java.awt.Color(255, 255, 255));
        txtNombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNombreKeyTyped(evt);
            }
        });

        txtApPaterno.setBackground(new java.awt.Color(255, 255, 255));
        txtApPaterno.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtApPaternoKeyTyped(evt);
            }
        });

        txtApMaterno.setBackground(new java.awt.Color(255, 255, 255));
        txtApMaterno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtApMaternoActionPerformed(evt);
            }
        });
        txtApMaterno.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtApMaternoKeyTyped(evt);
            }
        });

        txtTel.setBackground(new java.awt.Color(255, 255, 255));
        txtTel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTelActionPerformed(evt);
            }
        });
        txtTel.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtTelKeyTyped(evt);
            }
        });

        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Kilos Robados");

        txtTrampa.setBackground(new java.awt.Color(255, 255, 255));
        txtTrampa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTrampaActionPerformed(evt);
            }
        });
        txtTrampa.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtTrampaKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblApPaterno)
                    .addComponent(lblAPnaterno)
                    .addComponent(lblNombre)
                    .addComponent(lblTel)
                    .addComponent(jLabel2))
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(txtTrampa, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtNombre, javax.swing.GroupLayout.DEFAULT_SIZE, 156, Short.MAX_VALUE)
                                .addComponent(txtApPaterno)
                                .addComponent(txtApMaterno))
                            .addComponent(txtTel, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(18, Short.MAX_VALUE))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(111, 111, 111)
                .addComponent(lblSigId, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(lblSigId, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblNombre)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblApPaterno)
                    .addComponent(txtApPaterno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAPnaterno)
                    .addComponent(txtApMaterno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtTel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTel))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTrampa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        btbGuardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/botones_smoke (mejorados)/Guardar/save_norm.png"))); // NOI18N
        btbGuardar.setBorder(null);
        btbGuardar.setBorderPainted(false);
        btbGuardar.setFocusPainted(false);
        btbGuardar.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/botones_smoke (mejorados)/Guardar/save_press.png"))); // NOI18N
        btbGuardar.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/botones_smoke (mejorados)/Guardar/save_roll.png"))); // NOI18N
        btbGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btbGuardarActionPerformed(evt);
            }
        });

        btnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/botones_smoke (mejorados)/Cancelar/canc_norm.png"))); // NOI18N
        btnCancelar.setBorder(null);
        btnCancelar.setBorderPainted(false);
        btnCancelar.setFocusPainted(false);
        btnCancelar.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/botones_smoke (mejorados)/Cancelar/canc_press.png"))); // NOI18N
        btnCancelar.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/botones_smoke (mejorados)/Cancelar/canc_roll.png"))); // NOI18N
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/cliente_1.png"))); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(btbGuardar))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(20, 20, 20)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 381, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCancelar))
                .addContainerGap(25, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 36, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btbGuardar)
                    .addComponent(btnCancelar, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(18, 18, 18))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtApMaternoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtApMaternoActionPerformed
        
    }//GEN-LAST:event_txtApMaternoActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btbGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btbGuardarActionPerformed
        if(this.altaClienteT == true){
            if((this.txtNombre.getText().length() >0) && (this.txtApPaterno.getText().length() >0) && (this.txtApMaterno.getText().length()>0) && (this.txtTel.getText().length()>=10)  && (this.txtTrampa).getText().length()>0
                    && !(this.txtNombre.getText().trim().isEmpty()) && !(this.txtApPaterno.getText().trim().isEmpty()) && !(this.txtApMaterno.getText().trim().isEmpty()) && !(this.txtTel.getText().trim().isEmpty())
                    && !(this.txtTrampa.getText().trim().isEmpty())){
                Cliente c = new Cliente();
                c.ponerIdCliente(0);
                c.ponerNombreCliente(this.txtNombre.getText().trim());
                c.ponerApPaterno(this.txtApPaterno.getText().trim());
                c.ponerApMaterno(this.txtApMaterno.getText().trim());
                c.ponerTelefono(this.txtTel.getText().trim());
                c.setKilosRobados(Double.parseDouble(this.txtTrampa.getText().trim()));
                DAOCliente daoCliente = new DAOCliente();
                Integer resp = daoCliente.ageregarCliente(c);
                if(resp ==1){
                    JOptionPane.showMessageDialog(null, "El cliente se agrego correctamente", "Aviso", JOptionPane.INFORMATION_MESSAGE);
                }
                else{
                    JOptionPane.showMessageDialog(null, "Ocurrio un Error", "Error", JOptionPane.ERROR_MESSAGE);
                }
                this.setVisible(false);
            }
            else{
                if (this.txtTel.getText().length() < 10) {
                    
                    JOptionPane.showMessageDialog(null, "Número de Telefono no Valido", "Error", JOptionPane.ERROR_MESSAGE);
                }
                JOptionPane.showMessageDialog(null, "Los datos estan Incorrectos, intente otra vez", "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
        else{
            if((this.txtNombre.getText().length() >0) && (this.txtApPaterno.getText().length() >0) && (this.txtApMaterno.getText().length()>0) && (this.txtTel.getText().length()>=10) && 
                     (!(this.txtNombre.getText().trim().isEmpty()) && !(this.txtApPaterno.getText().trim().isEmpty()) && !(this.txtApMaterno.getText().trim().isEmpty())
                    && !(this.txtTel.getText().trim().isEmpty()))){
                
                Cliente c = new Cliente();   
                c.ponerIdCliente(Long.parseLong(this.lblSigId.getText()));
                c.ponerNombreCliente(this.txtNombre.getText().trim());
                c.ponerApPaterno(this.txtApPaterno.getText().trim());
                c.ponerApMaterno(this.txtApMaterno.getText().trim());
                c.ponerTelefono(this.txtTel.getText().trim());
                c.setKilosRobados(Double.parseDouble(this.txtTrampa.getText().trim()));
                DAOCliente daoCliente= new DAOCliente();
                Integer resultado = daoCliente.actualizarCliente(c);
                if(resultado ==1){
                    JOptionPane.showMessageDialog(null, "Registro Actualizado", "Aviso", JOptionPane.INFORMATION_MESSAGE);
                }else{
                    JOptionPane.showMessageDialog(null, "Error al Actualizar", "Error", JOptionPane.ERROR_MESSAGE);
                }
                this.setVisible(false);
            }
            else{
                if (this.txtTel.getText().length() < 10) {
                    
                    JOptionPane.showMessageDialog(null, "Número de Telefono no Valido", "Error", JOptionPane.ERROR_MESSAGE);
                }
                JOptionPane.showMessageDialog(null, "Los datos estan Incorrectos, intente otra vez", "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_btbGuardarActionPerformed

    private void txtNombreKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNombreKeyTyped
            char letra = evt.getKeyChar();
        if((letra < 'a' || letra > 'z') && (letra < 'A' || letra > 'Z') && (letra != 32) && (letra != '\u00f1') && (letra != '\u00d1')
        && (letra != '\u002E') && (letra != 'á') && (letra != 'é') && (letra != 'í') && (letra != 'ó') && (letra != 'ú') && 
        (letra != 'Á') && (letra != 'É') && (letra != 'Í') && (letra != 'Ó') && (letra != 'Ú') && (letra != 8)){
            evt.consume();
            Toolkit.getDefaultToolkit().beep();
        }
        if(this.txtNombre.getText().length() >= 30){
            evt.consume();
            Toolkit.getDefaultToolkit().beep();
        }
        char txtNombre=  evt.getKeyChar();
        if(Character.isDigit(txtNombre)){
            getToolkit().beep();
            evt.consume();
            JOptionPane.showMessageDialog(rootPane,"Ingrese solo Letras");
        }
        
        
    }//GEN-LAST:event_txtNombreKeyTyped

    private void txtApPaternoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtApPaternoKeyTyped
        char letra = evt.getKeyChar();
        if((letra < 'a' || letra > 'z') && (letra < 'A' || letra > 'Z') && (letra != 32) && (letra != '\u00f1') && (letra != '\u00d1')
        && (letra != '\u002E') && (letra != 'á') && (letra != 'é') && (letra != 'í') && (letra != 'ó') && (letra != 'ú') && 
        (letra != 'Á') && (letra != 'É') && (letra != 'Í') && (letra != 'Ó') && (letra != 'Ú') && (letra != 8)){
            evt.consume();
            Toolkit.getDefaultToolkit().beep();
        }
        if(this.txtApPaterno.getText().length() >= 30){
            evt.consume();
            Toolkit.getDefaultToolkit().beep();
        }
        char txtApPaterno=  evt.getKeyChar();
        if(Character.isDigit(txtApPaterno)){
            getToolkit().beep();
            evt.consume();
            JOptionPane.showMessageDialog(rootPane,"Ingrese solo Letras");
        }
    }//GEN-LAST:event_txtApPaternoKeyTyped

    private void txtApMaternoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtApMaternoKeyTyped
          char letra = evt.getKeyChar();
        if((letra < 'a' || letra > 'z') && (letra < 'A' || letra > 'Z') && (letra != 32) && (letra != '\u00f1') && (letra != '\u00d1')
        && (letra != '\u002E') && (letra != 'á') && (letra != 'é') && (letra != 'í') && (letra != 'ó') && (letra != 'ú') && 
        (letra != 'Á') && (letra != 'É') && (letra != 'Í') && (letra != 'Ó') && (letra != 'Ú') && (letra != 8)){
            evt.consume();
            Toolkit.getDefaultToolkit().beep();
        }
        if(this.txtApMaterno.getText().length() >= 30){
            evt.consume();
            Toolkit.getDefaultToolkit().beep();
        }
        char txtApMaterno=  evt.getKeyChar();
        if(Character.isDigit(txtApMaterno)){
            getToolkit().beep();
            evt.consume();
            JOptionPane.showMessageDialog(rootPane,"Ingrese solo Letras");
        }
    }//GEN-LAST:event_txtApMaternoKeyTyped

    private void txtTelKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTelKeyTyped
        char txtTel=  evt.getKeyChar();
        if (txtTel < '0' || txtTel >'9') {
            evt.consume();
        }
        if(Character.isLetter(txtTel)){
            getToolkit().beep();
            evt.consume();
            JOptionPane.showMessageDialog(rootPane,"Ingrese solo Números");
        }
        if (this.txtTel.getText().length() >=10) {
           evt.consume();
        }
    }//GEN-LAST:event_txtTelKeyTyped

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowActivated

    private void txtTelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTelActionPerformed

    private void txtTrampaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTrampaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTrampaActionPerformed

    private void txtTrampaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTrampaKeyTyped
        InputMap map2 = this.txtTrampa.getInputMap(JTextField.WHEN_FOCUSED);
        map2.put(KeyStroke.getKeyStroke(KeyEvent.VK_V, Event.CTRL_MASK),"null");

        
        char c  = evt.getKeyChar();
        
        if(!Character.isDigit(c) && c!= '.'){
                    evt.consume();
                
        } if(c == '.' && txtTrampa.getText().contains(".")){
                    evt.consume();
        }
      
    }//GEN-LAST:event_txtTrampaKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmAltaClienteTrampa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmAltaClienteTrampa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmAltaClienteTrampa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmAltaClienteTrampa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmAltaClienteTrampa().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btbGuardar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JInternalFrame jInternalFrame1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JLabel lblAPnaterno;
    private javax.swing.JLabel lblApPaterno;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblSigId;
    private javax.swing.JLabel lblTel;
    private javax.swing.JTextField txtApMaterno;
    private javax.swing.JTextField txtApPaterno;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtTel;
    private javax.swing.JTextField txtTrampa;
    // End of variables declaration//GEN-END:variables
}
